CREATE OR REPLACE TABLE escolas_alunos AS
SELECT 
	re.dre ,
	re.codesc ,
	re.tipoesc ,
	re.nomesc ,
	re.diretoria ,
	re.subpref ,
	re.setor,
	re.situacao,
	re.coddist ,
	re.fx_etaria ,
	re.rede,
	re.endereco ,
	re.bairro ,
	re.cep,
	re.latitude ,
	re.longitude ,
	re.dt_criacao ,
	re.dt_ini_func ,
	re.dt_ini_conv ,
	re.dt_autoriza ,
	re.database ,
	re2.ano,
	re2.modal,
	re2.descserie ,
	re2.periodo ,
	re2.turno,
	re2.descturno,
	re2.sexo ,
	re2.idade,
	re2.nee,
	re2.raca ,
	re2.qtde ,
FROM main.raw_escolas re 
LEFT JOIN main.raw_estudantes re2 ON re2.codesc = re.codesc;